name: HACS validation

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: hacs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
          ignore: "topics issues"
