name: Hassfest

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "15 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: hassfest-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
